name: drl-crypto
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - jupyter
  - tqdm
  - scipy
  - gym
  - pip
  - pip:
      - wandb
      - torchmetrics
      - yfinance
